/*
 * Firmatek Downloads API
 * Downloads API for accessing mission Downloads in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekDownloadsApi);
  }
}(this, function(expect, FirmatekDownloadsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirmatekDownloadsApi.DownloadsApi();
  });

  describe('(package)', function() {
    describe('DownloadsApi', function() {
      describe('getAvailableDownloads', function() {
        it('should call getAvailableDownloads successfully', function(done) {
          // TODO: uncomment, update parameter values for getAvailableDownloads call and complete the assertions
          /*

          instance.getAvailableDownloads(missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekDownloadsApi.AvailableDownload);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDownloadJobStatus', function() {
        it('should call getDownloadJobStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for getDownloadJobStatus call and complete the assertions
          /*

          instance.getDownloadJobStatus(downloadJobId, missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekDownloadsApi.DownloadJob);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDownloadJobsList', function() {
        it('should call getDownloadJobsList successfully', function(done) {
          // TODO: uncomment, update parameter values for getDownloadJobsList call and complete the assertions
          /*

          instance.getDownloadJobsList(missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekDownloadsApi.DownloadJob);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postDownloadJobsList', function() {
        it('should call postDownloadJobsList successfully', function(done) {
          // TODO: uncomment, update parameter values for postDownloadJobsList call and complete the assertions
          /*

          instance.postDownloadJobsList(body, missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekDownloadsApi.DownloadJob);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
