/*
 * Application Authorization API
 * API for authenticating client credentials to be able to access the Kespry Platform APIs
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApplicationAuthorizationApi);
  }
}(this, function(expect, ApplicationAuthorizationApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Auth', function() {
      beforeEach(function() {
        instance = new ApplicationAuthorizationApi.Auth();
      });

      it('should create an instance of Auth', function() {
        // TODO: update the code to test Auth
        expect(instance).to.be.a(ApplicationAuthorizationApi.Auth);
      });

      it('should have the property accessToken (base name: "access_token")', function() {
        // TODO: update the code to test the property accessToken
        expect(instance).to.have.property('accessToken');
        // expect(instance.accessToken).to.be(expectedValueLiteral);
      });

      it('should have the property tokenType (base name: "tokenType")', function() {
        // TODO: update the code to test the property tokenType
        expect(instance).to.have.property('tokenType');
        // expect(instance.tokenType).to.be(expectedValueLiteral);
      });

      it('should have the property issuedAt (base name: "issuedAt")', function() {
        // TODO: update the code to test the property issuedAt
        expect(instance).to.have.property('issuedAt');
        // expect(instance.issuedAt).to.be(expectedValueLiteral);
      });

      it('should have the property expiresIn (base name: "expiresIn")', function() {
        // TODO: update the code to test the property expiresIn
        expect(instance).to.have.property('expiresIn');
        // expect(instance.expiresIn).to.be(expectedValueLiteral);
      });

      it('should have the property clientID (base name: "clientID")', function() {
        // TODO: update the code to test the property clientID
        expect(instance).to.have.property('clientID');
        // expect(instance.clientID).to.be(expectedValueLiteral);
      });

      it('should have the property org (base name: "org")', function() {
        // TODO: update the code to test the property org
        expect(instance).to.have.property('org');
        // expect(instance.org).to.be(expectedValueLiteral);
      });

    });
  });

}));
