/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.ComparisonSurface = factory(root.FirmatekMissionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ComparisonSurface model module.
   * @module model/ComparisonSurface
   * @version 1.0
   */

  /**
   * Constructs a new <code>ComparisonSurface</code>.
   * @alias module:model/ComparisonSurface
   * @class
   * @param id {Number} Comparison surface record ID
   */
  var exports = function(id) {
    this.id = id;
  };

  /**
   * Constructs a <code>ComparisonSurface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComparisonSurface} obj Optional instance to populate.
   * @return {module:model/ComparisonSurface} The populated <code>ComparisonSurface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('comparison_surface_id'))
        obj.comparisonSurfaceId = ApiClient.convertToType(data['comparison_surface_id'], 'Number');
      if (data.hasOwnProperty('comparison_surface_type'))
        obj.comparisonSurfaceType = ApiClient.convertToType(data['comparison_surface_type'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('elevation'))
        obj.elevation = ApiClient.convertToType(data['elevation'], 'String');
      if (data.hasOwnProperty('geojson'))
        obj.geojson = ApiClient.convertToType(data['geojson'], Object);
    }
    return obj;
  }

  /**
   * Comparison surface record ID
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * ID of the referenced surface (known surface or image)
   * @member {Number} comparisonSurfaceId
   */
  exports.prototype.comparisonSurfaceId = undefined;

  /**
   * Surface type: BasePoints, Image, FixedElevation, or KnownSurface
   * @member {String} comparisonSurfaceType
   */
  exports.prototype.comparisonSurfaceType = undefined;

  /**
   * Display name of the comparison surface
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Fixed elevation value when comparison_surface_type is FixedElevation
   * @member {String} elevation
   */
  exports.prototype.elevation = undefined;

  /**
   * Geometry of the comparison surface as a GeoJSON object in WGS84
   * @member {Object} geojson
   */
  exports.prototype.geojson = undefined;


  return exports;

}));
