/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.CreateDownloadRequest = factory(root.FirmatekMissionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CreateDownloadRequest model module.
   * @module model/CreateDownloadRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>CreateDownloadRequest</code>.
   * @alias module:model/CreateDownloadRequest
   * @class
   * @param downloadType {String} Must match the 'name' of an available download for this mission
   */
  var exports = function(downloadType) {
    this.downloadType = downloadType;
  };

  /**
   * Constructs a <code>CreateDownloadRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateDownloadRequest} obj Optional instance to populate.
   * @return {module:model/CreateDownloadRequest} The populated <code>CreateDownloadRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('download_type'))
        obj.downloadType = ApiClient.convertToType(data['download_type'], 'String');
      if (data.hasOwnProperty('download_options'))
        obj.downloadOptions = ApiClient.convertToType(data['download_options'], Object);
    }
    return obj;
  }

  /**
   * Must match the 'name' of an available download for this mission
   * @member {String} downloadType
   */
  exports.prototype.downloadType = undefined;

  /**
   * Option values keyed by param name, e.g. {\"file_type\": \"png\"}
   * @member {Object} downloadOptions
   */
  exports.prototype.downloadOptions = undefined;


  return exports;

}));
