/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.DownloadParam = factory(root.FirmatekMissionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DownloadParam model module.
   * @module model/DownloadParam
   * @version 1.0
   */

  /**
   * Constructs a new <code>DownloadParam</code>.
   * @alias module:model/DownloadParam
   * @class
   * @param name {String} Option key to supply in download_options
   */
  var exports = function(name) {
    this.name = name;
  };

  /**
   * Constructs a <code>DownloadParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DownloadParam} obj Optional instance to populate.
   * @return {module:model/DownloadParam} The populated <code>DownloadParam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('param_type'))
        obj.paramType = ApiClient.convertToType(data['param_type'], 'String');
      if (data.hasOwnProperty('required'))
        obj.required = ApiClient.convertToType(data['required'], 'Boolean');
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], Object);
    }
    return obj;
  }

  /**
   * Human-readable label
   * @member {String} label
   */
  exports.prototype.label = undefined;

  /**
   * Option key to supply in download_options
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * One of: select, range, bool
   * @member {String} paramType
   */
  exports.prototype.paramType = undefined;

  /**
   * Whether the option must be supplied
   * @member {Boolean} required
   */
  exports.prototype.required = undefined;

  /**
   * Allowed values for a select, [min, max] for a range, or [true, false] for a bool
   * @member {Object} values
   */
  exports.prototype.values = undefined;


  return exports;

}));
