/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.KnownSurface = factory(root.FirmatekMissionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The KnownSurface model module.
   * @module model/KnownSurface
   * @version 1.0
   */

  /**
   * Constructs a new <code>KnownSurface</code>.
   * @alias module:model/KnownSurface
   * @class
   * @param id {Number} Known surface ID
   * @param surfaceName {String} Name of the known surface
   */
  var exports = function(id, surfaceName) {
    this.id = id;
    this.surfaceName = surfaceName;
  };

  /**
   * Constructs a <code>KnownSurface</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KnownSurface} obj Optional instance to populate.
   * @return {module:model/KnownSurface} The populated <code>KnownSurface</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('surface_name'))
        obj.surfaceName = ApiClient.convertToType(data['surface_name'], 'String');
      if (data.hasOwnProperty('surface_description'))
        obj.surfaceDescription = ApiClient.convertToType(data['surface_description'], 'String');
      if (data.hasOwnProperty('review_status'))
        obj.reviewStatus = ApiClient.convertToType(data['review_status'], 'String');
      if (data.hasOwnProperty('surface_image_file_name'))
        obj.surfaceImageFileName = ApiClient.convertToType(data['surface_image_file_name'], 'String');
      if (data.hasOwnProperty('surface_image_content_type'))
        obj.surfaceImageContentType = ApiClient.convertToType(data['surface_image_content_type'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
    }
    return obj;
  }

  /**
   * Known surface ID
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * Name of the known surface
   * @member {String} surfaceName
   */
  exports.prototype.surfaceName = undefined;

  /**
   * Description of the known surface
   * @member {String} surfaceDescription
   */
  exports.prototype.surfaceDescription = undefined;

  /**
   * Review status of the surface model
   * @member {String} reviewStatus
   */
  exports.prototype.reviewStatus = undefined;

  /**
   * File name of the surface image attachment
   * @member {String} surfaceImageFileName
   */
  exports.prototype.surfaceImageFileName = undefined;

  /**
   * MIME type of the surface image attachment
   * @member {String} surfaceImageContentType
   */
  exports.prototype.surfaceImageContentType = undefined;

  /**
   * Date the known surface was created (UTC, format 'YYYY-MM-DD HH:MM:SS')
   * @member {String} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * Date the known surface was last updated (UTC, format 'YYYY-MM-DD HH:MM:SS')
   * @member {String} updatedAt
   */
  exports.prototype.updatedAt = undefined;


  return exports;

}));
