/*
 * Firmatek Missions API
 * Missions API for accessing Missions in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.MarkerVolume = factory(root.FirmatekMissionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MarkerVolume model module.
   * @module model/MarkerVolume
   * @version 1.0
   */

  /**
   * Constructs a new <code>MarkerVolume</code>.
   * @alias module:model/MarkerVolume
   * @class
   * @param num {String} Pile #
   * @param name {String} Name
   */
  var exports = function(num, name) {
    this.num = num;
    this.name = name;
  };

  /**
   * Constructs a <code>MarkerVolume</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MarkerVolume} obj Optional instance to populate.
   * @return {module:model/MarkerVolume} The populated <code>MarkerVolume</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('num'))
        obj.num = ApiClient.convertToType(data['num'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('surface_desc'))
        obj.surfaceDesc = ApiClient.convertToType(data['surface_desc'], 'String');
      if (data.hasOwnProperty('sku'))
        obj.sku = ApiClient.convertToType(data['sku'], 'String');
      if (data.hasOwnProperty('surfaceArea'))
        obj.surfaceArea = ApiClient.convertToType(data['surfaceArea'], 'Number');
      if (data.hasOwnProperty('perimeter'))
        obj.perimeter = ApiClient.convertToType(data['perimeter'], 'Number');
      if (data.hasOwnProperty('cutVolume'))
        obj.cutVolume = ApiClient.convertToType(data['cutVolume'], 'Number');
      if (data.hasOwnProperty('fillVolume'))
        obj.fillVolume = ApiClient.convertToType(data['fillVolume'], 'Number');
      if (data.hasOwnProperty('threshold'))
        obj.threshold = ApiClient.convertToType(data['threshold'], 'Number');
      if (data.hasOwnProperty('offset'))
        obj.offset = ApiClient.convertToType(data['offset'], 'Number');
      if (data.hasOwnProperty('computedDensity'))
        obj.computedDensity = ApiClient.convertToType(data['computedDensity'], 'Number');
      if (data.hasOwnProperty('cutMass'))
        obj.cutMass = ApiClient.convertToType(data['cutMass'], 'Number');
      if (data.hasOwnProperty('fillMass'))
        obj.fillMass = ApiClient.convertToType(data['fillMass'], 'Number');
      if (data.hasOwnProperty('usesExtracted'))
        obj.usesExtracted = ApiClient.convertToType(data['usesExtracted'], 'Boolean');
    }
    return obj;
  }

  /**
   * Pile #
   * @member {String} num
   */
  exports.prototype.num = undefined;

  /**
   * Name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Description
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * Surface Description
   * @member {String} surfaceDesc
   */
  exports.prototype.surfaceDesc = undefined;

  /**
   * SKU Number
   * @member {String} sku
   */
  exports.prototype.sku = undefined;

  /**
   * Area (m2)
   * @member {Number} surfaceArea
   */
  exports.prototype.surfaceArea = undefined;

  /**
   * Perimeter (m)
   * @member {Number} perimeter
   */
  exports.prototype.perimeter = undefined;

  /**
   * Cut Volume
   * @member {Number} cutVolume
   */
  exports.prototype.cutVolume = undefined;

  /**
   * Fill Volume
   * @member {Number} fillVolume
   */
  exports.prototype.fillVolume = undefined;

  /**
   * Minimum Threshold
   * @member {Number} threshold
   */
  exports.prototype.threshold = undefined;

  /**
   * Offset
   * @member {Number} offset
   */
  exports.prototype.offset = undefined;

  /**
   * Density
   * @member {Number} computedDensity
   */
  exports.prototype.computedDensity = undefined;

  /**
   * Cut Mass
   * @member {Number} cutMass
   */
  exports.prototype.cutMass = undefined;

  /**
   * Fill Mass
   * @member {Number} fillMass
   */
  exports.prototype.fillMass = undefined;

  /**
   * Uses Extracted
   * @member {Boolean} usesExtracted
   */
  exports.prototype.usesExtracted = undefined;


  return exports;

}));
