/*
 * Firmatek Missions API
 * Missions API for accessing Missions in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.Site = factory(root.FirmatekMissionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Site model module.
   * @module model/Site
   * @version 1.0
   */

  /**
   * Constructs a new <code>Site</code>.
   * @alias module:model/Site
   * @class
   * @param id {Number} Site ID
   * @param name {String} Site name
   * @param customerId {Number} Customer ID
   */
  var exports = function(id, name, customerId) {
    this.id = id;
    this.name = name;
    this.customerId = customerId;
  };

  /**
   * Constructs a <code>Site</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Site} obj Optional instance to populate.
   * @return {module:model/Site} The populated <code>Site</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('customer_id'))
        obj.customerId = ApiClient.convertToType(data['customer_id'], 'Number');
      if (data.hasOwnProperty('center_lat'))
        obj.centerLat = ApiClient.convertToType(data['center_lat'], 'Number');
      if (data.hasOwnProperty('center_lng'))
        obj.centerLng = ApiClient.convertToType(data['center_lng'], 'Number');
      if (data.hasOwnProperty('outline'))
        obj.outline = ApiClient.convertToType(data['outline'], Object);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('update_at'))
        obj.updateAt = ApiClient.convertToType(data['update_at'], 'String');
    }
    return obj;
  }

  /**
   * Site ID
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * Site name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Customer ID
   * @member {Number} customerId
   */
  exports.prototype.customerId = undefined;

  /**
   * Center latitude in WGS84
   * @member {Number} centerLat
   */
  exports.prototype.centerLat = undefined;

  /**
   * Center longitude in WGS84
   * @member {Number} centerLng
   */
  exports.prototype.centerLng = undefined;

  /**
   * Site outline as a GeoJson format in WGS84
   * @member {Object} outline
   */
  exports.prototype.outline = undefined;

  /**
   * Date the site was created
   * @member {String} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * Date the site was update
   * @member {String} updateAt
   */
  exports.prototype.updateAt = undefined;


  return exports;

}));
