/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekMissionsApi);
  }
}(this, function(expect, FirmatekMissionsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirmatekMissionsApi.DownloadsApi();
  });

  describe('(package)', function() {
    describe('DownloadsApi', function() {
      describe('getAvailableDownloads', function() {
        it('should call getAvailableDownloads successfully', function(done) {
          // TODO: uncomment, update parameter values for getAvailableDownloads call and complete the assertions
          /*
          var missionId = 56;
          var siteId = 56;

          instance.getAvailableDownloads(missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekMissionsApi.AvailableDownload);
              expect(data.filename).to.be.a('string');
              expect(data.filename).to.be("Orthomosaic");
              expect(data.label).to.be.a('string');
              expect(data.label).to.be("Orthomosaic");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("ORTHO");
              expect(data.note).to.be.a('string');
              expect(data.note).to.be("");
              {
                let dataCtr = data.params;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(FirmatekMissionsApi.DownloadParam);
                  expect(data.label).to.be.a('string');
                  expect(data.label).to.be("File Type");
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("file_type");
                  expect(data.paramType).to.be.a('string');
                  expect(data.paramType).to.be("select");
                  expect(data.required).to.be.a('boolean');
                  expect(data.required).to.be(true);
                  expect(data.values).to.be.a(Object);
                  expect(data.values).to.be();
  
                        }
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDownloadJobStatus', function() {
        it('should call getDownloadJobStatus successfully', function(done) {
          // TODO: uncomment, update parameter values for getDownloadJobStatus call and complete the assertions
          /*
          var downloadJobId = "downloadJobId_example";
          var missionId = 56;
          var siteId = 56;

          instance.getDownloadJobStatus(downloadJobId, missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekMissionsApi.DownloadJob);
            expect(data.jobId).to.be.a('string');
            expect(data.jobId).to.be("a8937cd4-4070-4b8e-8235-7dbd98886e3c");
            expect(data.createdAt).to.be.a('string');
            expect(data.createdAt).to.be("2026-06-10T17:01:30Z");
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("SUCCESS");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("ORTHO");
            expect(data.options).to.be.a(Object);
            expect(data.options).to.be();
            expect(data.presignedUrl).to.be.a('string');
            expect(data.presignedUrl).to.be("");
            expect(data.fileStatus).to.be.a('string');
            expect(data.fileStatus).to.be("exists");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDownloadJobsList', function() {
        it('should call getDownloadJobsList successfully', function(done) {
          // TODO: uncomment, update parameter values for getDownloadJobsList call and complete the assertions
          /*
          var missionId = 56;
          var siteId = 56;

          instance.getDownloadJobsList(missionId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekMissionsApi.DownloadJob);
              expect(data.jobId).to.be.a('string');
              expect(data.jobId).to.be("a8937cd4-4070-4b8e-8235-7dbd98886e3c");
              expect(data.createdAt).to.be.a('string');
              expect(data.createdAt).to.be("2026-06-10T17:01:30Z");
              expect(data.status).to.be.a('string');
              expect(data.status).to.be("SUCCESS");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("ORTHO");
              expect(data.options).to.be.a(Object);
              expect(data.options).to.be();
              expect(data.presignedUrl).to.be.a('string');
              expect(data.presignedUrl).to.be("");
              expect(data.fileStatus).to.be.a('string');
              expect(data.fileStatus).to.be("exists");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postDownloadJobsList', function() {
        it('should call postDownloadJobsList successfully', function(done) {
          // TODO: uncomment, update parameter values for postDownloadJobsList call and complete the assertions
          /*
          var missionId = 56;
          var siteId = 56;
          var payload = new FirmatekMissionsApi.CreateDownloadRequest();
          payload.downloadType = "ORTHO";
          payload.downloadOptions = ;

          instance.postDownloadJobsList(missionId, siteId, payload, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekMissionsApi.DownloadJob);
            expect(data.jobId).to.be.a('string');
            expect(data.jobId).to.be("a8937cd4-4070-4b8e-8235-7dbd98886e3c");
            expect(data.createdAt).to.be.a('string');
            expect(data.createdAt).to.be("2026-06-10T17:01:30Z");
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("SUCCESS");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("ORTHO");
            expect(data.options).to.be.a(Object);
            expect(data.options).to.be();
            expect(data.presignedUrl).to.be.a('string');
            expect(data.presignedUrl).to.be("");
            expect(data.fileStatus).to.be.a('string');
            expect(data.fileStatus).to.be("exists");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
