/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekMissionsApi);
  }
}(this, function(expect, FirmatekMissionsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirmatekMissionsApi.KnownSurfacesApi();
  });

  describe('(package)', function() {
    describe('KnownSurfacesApi', function() {
      describe('getKnownSurfaceDetail', function() {
        it('should call getKnownSurfaceDetail successfully', function(done) {
          // TODO: uncomment, update parameter values for getKnownSurfaceDetail call and complete the assertions
          /*
          var knownSurfaceId = 56;
          var siteId = 56;

          instance.getKnownSurfaceDetail(knownSurfaceId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekMissionsApi.KnownSurface);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(42);
            expect(data.surfaceName).to.be.a('string');
            expect(data.surfaceName).to.be("Base Grade");
            expect(data.surfaceDescription).to.be.a('string');
            expect(data.surfaceDescription).to.be("Pre-construction base grade survey");
            expect(data.reviewStatus).to.be.a('string');
            expect(data.reviewStatus).to.be("approved");
            expect(data.surfaceImageFileName).to.be.a('string');
            expect(data.surfaceImageFileName).to.be("base_grade.png");
            expect(data.surfaceImageContentType).to.be.a('string');
            expect(data.surfaceImageContentType).to.be("image/png");
            expect(data.createdAt).to.be.a('string');
            expect(data.createdAt).to.be("2024-01-10 09:00:00");
            expect(data.updatedAt).to.be.a('string');
            expect(data.updatedAt).to.be("2024-03-05 14:22:11");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getKnownSurfaceList', function() {
        it('should call getKnownSurfaceList successfully', function(done) {
          // TODO: uncomment, update parameter values for getKnownSurfaceList call and complete the assertions
          /*
          var siteId = 56;

          instance.getKnownSurfaceList(siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekMissionsApi.KnownSurface);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be(42);
              expect(data.surfaceName).to.be.a('string');
              expect(data.surfaceName).to.be("Base Grade");
              expect(data.surfaceDescription).to.be.a('string');
              expect(data.surfaceDescription).to.be("Pre-construction base grade survey");
              expect(data.reviewStatus).to.be.a('string');
              expect(data.reviewStatus).to.be("approved");
              expect(data.surfaceImageFileName).to.be.a('string');
              expect(data.surfaceImageFileName).to.be("base_grade.png");
              expect(data.surfaceImageContentType).to.be.a('string');
              expect(data.surfaceImageContentType).to.be("image/png");
              expect(data.createdAt).to.be.a('string');
              expect(data.createdAt).to.be("2024-01-10 09:00:00");
              expect(data.updatedAt).to.be.a('string');
              expect(data.updatedAt).to.be("2024-03-05 14:22:11");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
