/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekMissionsApi);
  }
}(this, function(expect, FirmatekMissionsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirmatekMissionsApi.ProductsApi();
  });

  describe('(package)', function() {
    describe('ProductsApi', function() {
      describe('getProductDetail', function() {
        it('should call getProductDetail successfully', function(done) {
          // TODO: uncomment, update parameter values for getProductDetail call and complete the assertions
          /*
          var productId = 56;
          var siteId = 56;

          instance.getProductDetail(productId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekMissionsApi.Product);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(781);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("Crushed Limestone");
            expect(data.siteId).to.be.a('number');
            expect(data.siteId).to.be(4821);
            expect(data.values).to.be.a(Object);
            expect(data.values).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProductList', function() {
        it('should call getProductList successfully', function(done) {
          // TODO: uncomment, update parameter values for getProductList call and complete the assertions
          /*
          var siteId = 56;

          instance.getProductList(siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekMissionsApi.Product);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be(781);
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("Crushed Limestone");
              expect(data.siteId).to.be.a('number');
              expect(data.siteId).to.be(4821);
              expect(data.values).to.be.a(Object);
              expect(data.values).to.be();
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
