/*
 * Firmatek Downloads API
 * Downloads API for accessing mission Downloads in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DownloadParam'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DownloadParam'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekDownloadsApi) {
      root.FirmatekDownloadsApi = {};
    }
    root.FirmatekDownloadsApi.AvailableDownload = factory(root.FirmatekDownloadsApi.ApiClient, root.FirmatekDownloadsApi.DownloadParam);
  }
}(this, function(ApiClient, DownloadParam) {
  'use strict';

  /**
   * The AvailableDownload model module.
   * @module model/AvailableDownload
   * @version 1.0
   */

  /**
   * Constructs a new <code>AvailableDownload</code>.
   * @alias module:model/AvailableDownload
   * @class
   * @param name {String} Download type identifier; supply this as download_type when creating a job
   */
  var exports = function(name) {
    this.name = name;
  };

  /**
   * Constructs a <code>AvailableDownload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AvailableDownload} obj Optional instance to populate.
   * @return {module:model/AvailableDownload} The populated <code>AvailableDownload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('filename'))
        obj.filename = ApiClient.convertToType(data['filename'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('note'))
        obj.note = ApiClient.convertToType(data['note'], 'String');
      if (data.hasOwnProperty('params'))
        obj.params = ApiClient.convertToType(data['params'], [DownloadParam]);
    }
    return obj;
  }

  /**
   * Base output filename
   * @member {String} filename
   */
  exports.prototype.filename = undefined;

  /**
   * Human-readable label
   * @member {String} label
   */
  exports.prototype.label = undefined;

  /**
   * Download type identifier; supply this as download_type when creating a job
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Advisory note about this download, if any
   * @member {String} note
   */
  exports.prototype.note = undefined;

  /**
   * Available options for this download
   * @member {Array.<module:model/DownloadParam>} params
   */
  exports.prototype.params = undefined;


  return exports;

}));
