/*
 * Firmatek Downloads API
 * Downloads API for accessing mission Downloads in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekDownloadsApi) {
      root.FirmatekDownloadsApi = {};
    }
    root.FirmatekDownloadsApi.DownloadJob = factory(root.FirmatekDownloadsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DownloadJob model module.
   * @module model/DownloadJob
   * @version 1.0
   */

  /**
   * Constructs a new <code>DownloadJob</code>.
   * @alias module:model/DownloadJob
   * @class
   * @param jobId {String} Download job ID; use it to poll status
   */
  var exports = function(jobId) {
    this.jobId = jobId;
  };

  /**
   * Constructs a <code>DownloadJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DownloadJob} obj Optional instance to populate.
   * @return {module:model/DownloadJob} The populated <code>DownloadJob</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('job_id'))
        obj.jobId = ApiClient.convertToType(data['job_id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('options'))
        obj.options = ApiClient.convertToType(data['options'], Object);
      if (data.hasOwnProperty('presigned_url'))
        obj.presignedUrl = ApiClient.convertToType(data['presigned_url'], 'String');
      if (data.hasOwnProperty('file_status'))
        obj.fileStatus = ApiClient.convertToType(data['file_status'], 'String');
    }
    return obj;
  }

  /**
   * Download job ID; use it to poll status
   * @member {String} jobId
   */
  exports.prototype.jobId = undefined;

  /**
   * Job creation time (UTC, ISO-8601, e.g. 2026-06-10T17:01:30Z)
   * @member {String} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * Job status: NEW, PENDING, QUEUED, STARTED, RUNNING, SCHEDULED, SUCCESS, FAILED, or STOPPED
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * Download type
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Options the job was created with
   * @member {Object} options
   */
  exports.prototype.options = undefined;

  /**
   * Time-limited (15-minute) S3 URL to download the output file; null until the job succeeds
   * @member {String} presignedUrl
   */
  exports.prototype.presignedUrl = undefined;

  /**
   * 'exists' when the output file is present, 'missing' if it is gone/expired, 'unknown' before the job produces output
   * @member {String} fileStatus
   */
  exports.prototype.fileStatus = undefined;


  return exports;

}));
