/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvailableDownload', 'model/CreateDownloadRequest', 'model/DownloadJob', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AvailableDownload'), require('../model/CreateDownloadRequest'), require('../model/DownloadJob'), require('../model/Error'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.DownloadsApi = factory(root.FirmatekMissionsApi.ApiClient, root.FirmatekMissionsApi.AvailableDownload, root.FirmatekMissionsApi.CreateDownloadRequest, root.FirmatekMissionsApi.DownloadJob, root.FirmatekMissionsApi.Error);
  }
}(this, function(ApiClient, AvailableDownload, CreateDownloadRequest, DownloadJob, Error) {
  'use strict';

  /**
   * Downloads service.
   * @module api/DownloadsApi
   * @version 1.0
   */

  /**
   * Constructs a new DownloadsApi. 
   * @alias module:api/DownloadsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAvailableDownloads operation.
     * @callback module:api/DownloadsApi~getAvailableDownloadsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AvailableDownload>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the downloads available for the specified mission, each with its configurable options.
     * @param {Number} missionId ID of the mission
     * @param {Number} siteId ID of the site
     * @param {module:api/DownloadsApi~getAvailableDownloadsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AvailableDownload>}
     */
    this.getAvailableDownloads = function(missionId, siteId, callback) {
      var postBody = null;

      // verify the required parameter 'missionId' is set
      if (missionId === undefined || missionId === null) {
        throw new Error("Missing the required parameter 'missionId' when calling getAvailableDownloads");
      }

      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling getAvailableDownloads");
      }


      var pathParams = {
        'mission_id': missionId,
        'site_id': siteId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AvailableDownload];

      return this.apiClient.callApi(
        '/downloads/v1/sites/{site_id}/missions/{mission_id}/available_downloads', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDownloadJobStatus operation.
     * @callback module:api/DownloadsApi~getDownloadJobStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DownloadJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the status of a single download job, polling the download service if the job is not yet in a terminal state.
     * @param {String} downloadJobId ID of the download job
     * @param {Number} missionId ID of the mission
     * @param {Number} siteId ID of the site
     * @param {module:api/DownloadsApi~getDownloadJobStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DownloadJob}
     */
    this.getDownloadJobStatus = function(downloadJobId, missionId, siteId, callback) {
      var postBody = null;

      // verify the required parameter 'downloadJobId' is set
      if (downloadJobId === undefined || downloadJobId === null) {
        throw new Error("Missing the required parameter 'downloadJobId' when calling getDownloadJobStatus");
      }

      // verify the required parameter 'missionId' is set
      if (missionId === undefined || missionId === null) {
        throw new Error("Missing the required parameter 'missionId' when calling getDownloadJobStatus");
      }

      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling getDownloadJobStatus");
      }


      var pathParams = {
        'download_job_id': downloadJobId,
        'mission_id': missionId,
        'site_id': siteId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DownloadJob;

      return this.apiClient.callApi(
        '/downloads/v1/sites/{site_id}/missions/{mission_id}/jobs/{download_job_id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDownloadJobsList operation.
     * @callback module:api/DownloadsApi~getDownloadJobsListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DownloadJob>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lists the download jobs for the specified mission, refreshing their status from the download service.
     * @param {Number} missionId ID of the mission
     * @param {Number} siteId ID of the site
     * @param {module:api/DownloadsApi~getDownloadJobsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DownloadJob>}
     */
    this.getDownloadJobsList = function(missionId, siteId, callback) {
      var postBody = null;

      // verify the required parameter 'missionId' is set
      if (missionId === undefined || missionId === null) {
        throw new Error("Missing the required parameter 'missionId' when calling getDownloadJobsList");
      }

      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling getDownloadJobsList");
      }


      var pathParams = {
        'mission_id': missionId,
        'site_id': siteId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [DownloadJob];

      return this.apiClient.callApi(
        '/downloads/v1/sites/{site_id}/missions/{mission_id}/jobs', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postDownloadJobsList operation.
     * @callback module:api/DownloadsApi~postDownloadJobsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DownloadJob} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Requests (creates) a new download job for the specified mission. download_type must match the 'name' of an available download.
     * @param {Number} missionId ID of the mission
     * @param {Number} siteId ID of the site
     * @param {module:model/CreateDownloadRequest} payload 
     * @param {module:api/DownloadsApi~postDownloadJobsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DownloadJob}
     */
    this.postDownloadJobsList = function(missionId, siteId, payload, callback) {
      var postBody = payload;

      // verify the required parameter 'missionId' is set
      if (missionId === undefined || missionId === null) {
        throw new Error("Missing the required parameter 'missionId' when calling postDownloadJobsList");
      }

      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling postDownloadJobsList");
      }

      // verify the required parameter 'payload' is set
      if (payload === undefined || payload === null) {
        throw new Error("Missing the required parameter 'payload' when calling postDownloadJobsList");
      }


      var pathParams = {
        'mission_id': missionId,
        'site_id': siteId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DownloadJob;

      return this.apiClient.callApi(
        '/downloads/v1/sites/{site_id}/missions/{mission_id}/jobs', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
