/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/KnownSurface'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/KnownSurface'));
  } else {
    // Browser globals (root is window)
    if (!root.FirmatekMissionsApi) {
      root.FirmatekMissionsApi = {};
    }
    root.FirmatekMissionsApi.KnownSurfacesApi = factory(root.FirmatekMissionsApi.ApiClient, root.FirmatekMissionsApi.Error, root.FirmatekMissionsApi.KnownSurface);
  }
}(this, function(ApiClient, Error, KnownSurface) {
  'use strict';

  /**
   * KnownSurfaces service.
   * @module api/KnownSurfacesApi
   * @version 1.0
   */

  /**
   * Constructs a new KnownSurfacesApi. 
   * @alias module:api/KnownSurfacesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getKnownSurfaceDetail operation.
     * @callback module:api/KnownSurfacesApi~getKnownSurfaceDetailCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KnownSurface} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a single known surface by ID. The known surface must be active on the specified site.
     * @param {Number} knownSurfaceId ID of the known surface
     * @param {Number} siteId ID of the site
     * @param {module:api/KnownSurfacesApi~getKnownSurfaceDetailCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KnownSurface}
     */
    this.getKnownSurfaceDetail = function(knownSurfaceId, siteId, callback) {
      var postBody = null;

      // verify the required parameter 'knownSurfaceId' is set
      if (knownSurfaceId === undefined || knownSurfaceId === null) {
        throw new Error("Missing the required parameter 'knownSurfaceId' when calling getKnownSurfaceDetail");
      }

      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling getKnownSurfaceDetail");
      }


      var pathParams = {
        'known_surface_id': knownSurfaceId,
        'site_id': siteId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = KnownSurface;

      return this.apiClient.callApi(
        '/known-surfaces/v1/sites/{site_id}/known-surfaces/{known_surface_id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getKnownSurfaceList operation.
     * @callback module:api/KnownSurfacesApi~getKnownSurfaceListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/KnownSurface>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all active known surfaces for the specified site.
     * @param {Number} siteId ID of the site
     * @param {module:api/KnownSurfacesApi~getKnownSurfaceListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/KnownSurface>}
     */
    this.getKnownSurfaceList = function(siteId, callback) {
      var postBody = null;

      // verify the required parameter 'siteId' is set
      if (siteId === undefined || siteId === null) {
        throw new Error("Missing the required parameter 'siteId' when calling getKnownSurfaceList");
      }


      var pathParams = {
        'site_id': siteId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apikey'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [KnownSurface];

      return this.apiClient.callApi(
        '/known-surfaces/v1/sites/{site_id}/known-surfaces', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
