/*
 * Firmatek Downloads API
 * Downloads API for accessing mission Downloads in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvailableDownload', 'model/CreateDownloadRequest', 'model/DownloadJob', 'model/DownloadParam', 'model/Error', 'api/DownloadsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AvailableDownload'), require('./model/CreateDownloadRequest'), require('./model/DownloadJob'), require('./model/DownloadParam'), require('./model/Error'), require('./api/DownloadsApi'));
  }
}(function(ApiClient, AvailableDownload, CreateDownloadRequest, DownloadJob, DownloadParam, Error, DownloadsApi) {
  'use strict';

  /**
   * Downloads_API_for_accessing_mission_Downloads_in_the_Kespry_Platform.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var FirmatekDownloadsApi = require('index'); // See note below*.
   * var xxxSvc = new FirmatekDownloadsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new FirmatekDownloadsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new FirmatekDownloadsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new FirmatekDownloadsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AvailableDownload model constructor.
     * @property {module:model/AvailableDownload}
     */
    AvailableDownload: AvailableDownload,
    /**
     * The CreateDownloadRequest model constructor.
     * @property {module:model/CreateDownloadRequest}
     */
    CreateDownloadRequest: CreateDownloadRequest,
    /**
     * The DownloadJob model constructor.
     * @property {module:model/DownloadJob}
     */
    DownloadJob: DownloadJob,
    /**
     * The DownloadParam model constructor.
     * @property {module:model/DownloadParam}
     */
    DownloadParam: DownloadParam,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The DownloadsApi service constructor.
     * @property {module:api/DownloadsApi}
     */
    DownloadsApi: DownloadsApi
  };

  return exports;
}));
