/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekMissionsApi);
  }
}(this, function(expect, FirmatekMissionsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ComparisonSurface', function() {
      beforeEach(function() {
        instance = new FirmatekMissionsApi.ComparisonSurface();
      });

      it('should create an instance of ComparisonSurface', function() {
        // TODO: update the code to test ComparisonSurface
        expect(instance).to.be.a(FirmatekMissionsApi.ComparisonSurface);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property comparisonSurfaceId (base name: "comparison_surface_id")', function() {
        // TODO: update the code to test the property comparisonSurfaceId
        expect(instance).to.have.property('comparisonSurfaceId');
        // expect(instance.comparisonSurfaceId).to.be(expectedValueLiteral);
      });

      it('should have the property comparisonSurfaceType (base name: "comparison_surface_type")', function() {
        // TODO: update the code to test the property comparisonSurfaceType
        expect(instance).to.have.property('comparisonSurfaceType');
        // expect(instance.comparisonSurfaceType).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property elevation (base name: "elevation")', function() {
        // TODO: update the code to test the property elevation
        expect(instance).to.have.property('elevation');
        // expect(instance.elevation).to.be(expectedValueLiteral);
      });

      it('should have the property geojson (base name: "geojson")', function() {
        // TODO: update the code to test the property geojson
        expect(instance).to.have.property('geojson');
        // expect(instance.geojson).to.be(expectedValueLiteral);
      });

    });
  });

}));
