/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekMissionsApi);
  }
}(this, function(expect, FirmatekMissionsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('KnownSurface', function() {
      beforeEach(function() {
        instance = new FirmatekMissionsApi.KnownSurface();
      });

      it('should create an instance of KnownSurface', function() {
        // TODO: update the code to test KnownSurface
        expect(instance).to.be.a(FirmatekMissionsApi.KnownSurface);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property surfaceName (base name: "surface_name")', function() {
        // TODO: update the code to test the property surfaceName
        expect(instance).to.have.property('surfaceName');
        // expect(instance.surfaceName).to.be(expectedValueLiteral);
      });

      it('should have the property surfaceDescription (base name: "surface_description")', function() {
        // TODO: update the code to test the property surfaceDescription
        expect(instance).to.have.property('surfaceDescription');
        // expect(instance.surfaceDescription).to.be(expectedValueLiteral);
      });

      it('should have the property reviewStatus (base name: "review_status")', function() {
        // TODO: update the code to test the property reviewStatus
        expect(instance).to.have.property('reviewStatus');
        // expect(instance.reviewStatus).to.be(expectedValueLiteral);
      });

      it('should have the property surfaceImageFileName (base name: "surface_image_file_name")', function() {
        // TODO: update the code to test the property surfaceImageFileName
        expect(instance).to.have.property('surfaceImageFileName');
        // expect(instance.surfaceImageFileName).to.be(expectedValueLiteral);
      });

      it('should have the property surfaceImageContentType (base name: "surface_image_content_type")', function() {
        // TODO: update the code to test the property surfaceImageContentType
        expect(instance).to.have.property('surfaceImageContentType');
        // expect(instance.surfaceImageContentType).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updated_at")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
