/*
 * Firmatek Missions API
 * Missions API for accessing Missions in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekMissionsApi);
  }
}(this, function(expect, FirmatekMissionsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Site', function() {
      beforeEach(function() {
        instance = new FirmatekMissionsApi.Site();
      });

      it('should create an instance of Site', function() {
        // TODO: update the code to test Site
        expect(instance).to.be.a(FirmatekMissionsApi.Site);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property customerId (base name: "customer_id")', function() {
        // TODO: update the code to test the property customerId
        expect(instance).to.have.property('customerId');
        // expect(instance.customerId).to.be(expectedValueLiteral);
      });

      it('should have the property centerLat (base name: "center_lat")', function() {
        // TODO: update the code to test the property centerLat
        expect(instance).to.have.property('centerLat');
        // expect(instance.centerLat).to.be(expectedValueLiteral);
      });

      it('should have the property centerLng (base name: "center_lng")', function() {
        // TODO: update the code to test the property centerLng
        expect(instance).to.have.property('centerLng');
        // expect(instance.centerLng).to.be(expectedValueLiteral);
      });

      it('should have the property outline (base name: "outline")', function() {
        // TODO: update the code to test the property outline
        expect(instance).to.have.property('outline');
        // expect(instance.outline).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updateAt (base name: "update_at")', function() {
        // TODO: update the code to test the property updateAt
        expect(instance).to.have.property('updateAt');
        // expect(instance.updateAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
