/*
 * Firmatek Missions API
 * Missions API for accessing Missions in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Marker', 'model/MarkerVolume', 'model/Mission', 'model/Site', 'api/V1Api'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Marker'), require('./model/MarkerVolume'), require('./model/Mission'), require('./model/Site'), require('./api/V1Api'));
  }
}(function(ApiClient, Marker, MarkerVolume, Mission, Site, V1Api) {
  'use strict';

  /**
   * Missions_API_for_accessing_Missions_in_the_Kespry_Platform.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var FirmatekMissionsApi = require('index'); // See note below*.
   * var xxxSvc = new FirmatekMissionsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new FirmatekMissionsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new FirmatekMissionsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new FirmatekMissionsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Marker model constructor.
     * @property {module:model/Marker}
     */
    Marker: Marker,
    /**
     * The MarkerVolume model constructor.
     * @property {module:model/MarkerVolume}
     */
    MarkerVolume: MarkerVolume,
    /**
     * The Mission model constructor.
     * @property {module:model/Mission}
     */
    Mission: Mission,
    /**
     * The Site model constructor.
     * @property {module:model/Site}
     */
    Site: Site,
    /**
     * The V1Api service constructor.
     * @property {module:api/V1Api}
     */
    V1Api: V1Api
  };

  return exports;
}));
