/*
 * Firmatek Missions API
 * Public API for accessing Sites, Missions, Markers, Volumes, Products, Known Surfaces, and Downloads in the Kespry Platform. Requests require a Bearer token obtained from the Authentication API (POST /api/auth/, see /api/auth/v1).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AvailableDownload', 'model/ComparisonSurface', 'model/CreateDownloadRequest', 'model/DownloadJob', 'model/DownloadParam', 'model/Error', 'model/KnownSurface', 'model/Marker', 'model/MarkerVolume', 'model/Mission', 'model/Product', 'model/Site', 'api/DownloadsApi', 'api/KnownSurfacesApi', 'api/ProductsApi', 'api/V1Api'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AvailableDownload'), require('./model/ComparisonSurface'), require('./model/CreateDownloadRequest'), require('./model/DownloadJob'), require('./model/DownloadParam'), require('./model/Error'), require('./model/KnownSurface'), require('./model/Marker'), require('./model/MarkerVolume'), require('./model/Mission'), require('./model/Product'), require('./model/Site'), require('./api/DownloadsApi'), require('./api/KnownSurfacesApi'), require('./api/ProductsApi'), require('./api/V1Api'));
  }
}(function(ApiClient, AvailableDownload, ComparisonSurface, CreateDownloadRequest, DownloadJob, DownloadParam, Error, KnownSurface, Marker, MarkerVolume, Mission, Product, Site, DownloadsApi, KnownSurfacesApi, ProductsApi, V1Api) {
  'use strict';

  /**
   * Public_API_for_accessing_Sites_Missions_Markers_Volumes_Products_Known_Surfaces_and_Downloads_in_the_Kespry_Platform__Requests_require_a_Bearer_token_obtained_from_the_Authentication_API__POST_apiauth_see_apiauthv1_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var FirmatekMissionsApi = require('index'); // See note below*.
   * var xxxSvc = new FirmatekMissionsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new FirmatekMissionsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new FirmatekMissionsApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new FirmatekMissionsApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AvailableDownload model constructor.
     * @property {module:model/AvailableDownload}
     */
    AvailableDownload: AvailableDownload,
    /**
     * The ComparisonSurface model constructor.
     * @property {module:model/ComparisonSurface}
     */
    ComparisonSurface: ComparisonSurface,
    /**
     * The CreateDownloadRequest model constructor.
     * @property {module:model/CreateDownloadRequest}
     */
    CreateDownloadRequest: CreateDownloadRequest,
    /**
     * The DownloadJob model constructor.
     * @property {module:model/DownloadJob}
     */
    DownloadJob: DownloadJob,
    /**
     * The DownloadParam model constructor.
     * @property {module:model/DownloadParam}
     */
    DownloadParam: DownloadParam,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The KnownSurface model constructor.
     * @property {module:model/KnownSurface}
     */
    KnownSurface: KnownSurface,
    /**
     * The Marker model constructor.
     * @property {module:model/Marker}
     */
    Marker: Marker,
    /**
     * The MarkerVolume model constructor.
     * @property {module:model/MarkerVolume}
     */
    MarkerVolume: MarkerVolume,
    /**
     * The Mission model constructor.
     * @property {module:model/Mission}
     */
    Mission: Mission,
    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product: Product,
    /**
     * The Site model constructor.
     * @property {module:model/Site}
     */
    Site: Site,
    /**
     * The DownloadsApi service constructor.
     * @property {module:api/DownloadsApi}
     */
    DownloadsApi: DownloadsApi,
    /**
     * The KnownSurfacesApi service constructor.
     * @property {module:api/KnownSurfacesApi}
     */
    KnownSurfacesApi: KnownSurfacesApi,
    /**
     * The ProductsApi service constructor.
     * @property {module:api/ProductsApi}
     */
    ProductsApi: ProductsApi,
    /**
     * The V1Api service constructor.
     * @property {module:api/V1Api}
     */
    V1Api: V1Api
  };

  return exports;
}));
