/*
 * Application Authorization API
 * API for authenticating client credentials to be able to access the Kespry Platform APIs
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApplicationAuthorizationApi);
  }
}(this, function(expect, ApplicationAuthorizationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApplicationAuthorizationApi.V1Api();
  });

  describe('(package)', function() {
    describe('V1Api', function() {
      describe('postLogin', function() {
        it('should call postLogin successfully', function(done) {
          // TODO: uncomment, update parameter values for postLogin call and complete the assertions
          /*
          var grantType = "client_credentials";
          var opts = {};
          opts.xFields = "xFields_example";

          instance.postLogin(grantType, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ApplicationAuthorizationApi.Auth);
            expect(data.accessToken).to.be.a('string');
            expect(data.accessToken).to.be("<YOUR ACCESS TOKEN>");
            expect(data.tokenType).to.be.a('string');
            expect(data.tokenType).to.be("BearerToken");
            expect(data.issuedAt).to.be.a('number');
            expect(data.issuedAt).to.be(1723029552023);
            expect(data.expiresIn).to.be.a('number');
            expect(data.expiresIn).to.be(36000);
            expect(data.clientID).to.be.a('string');
            expect(data.clientID).to.be("<YOUR CLIENT ID>");
            expect(data.org).to.be.a('string');
            expect(data.org).to.be("api.kespry.com");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
