/*
 * Firmatek Known Surfaces API
 * Known Surfaces API for accessing Known Surfaces in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekKnownSurfacesApi);
  }
}(this, function(expect, FirmatekKnownSurfacesApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirmatekKnownSurfacesApi.KnownSurfacesApi();
  });

  describe('(package)', function() {
    describe('KnownSurfacesApi', function() {
      describe('getKnownSurfaceDetail', function() {
        it('should call getKnownSurfaceDetail successfully', function(done) {
          // TODO: uncomment, update parameter values for getKnownSurfaceDetail call and complete the assertions
          /*

          instance.getKnownSurfaceDetail(knownSurfaceId, siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FirmatekKnownSurfacesApi.KnownSurface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getKnownSurfaceList', function() {
        it('should call getKnownSurfaceList successfully', function(done) {
          // TODO: uncomment, update parameter values for getKnownSurfaceList call and complete the assertions
          /*

          instance.getKnownSurfaceList(siteId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FirmatekKnownSurfacesApi.KnownSurface);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
