/*
 * Application Authorization API
 * API for authenticating client credentials to be able to access the Kespry Platform APIs
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Auth'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Auth'));
  } else {
    // Browser globals (root is window)
    if (!root.ApplicationAuthorizationApi) {
      root.ApplicationAuthorizationApi = {};
    }
    root.ApplicationAuthorizationApi.V1Api = factory(root.ApplicationAuthorizationApi.ApiClient, root.ApplicationAuthorizationApi.Auth);
  }
}(this, function(ApiClient, Auth) {
  'use strict';

  /**
   * V1 service.
   * @module api/V1Api
   * @version 1.0
   */

  /**
   * Constructs a new V1Api. 
   * @alias module:api/V1Api
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the postLogin operation.
     * @callback module:api/V1Api~postLoginCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Auth} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} grantType Grant type
     * @param {Object} opts Optional parameters
     * @param {String} opts.xFields An optional fields mask
     * @param {module:api/V1Api~postLoginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Auth}
     */
    this.postLogin = function(grantType, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'grantType' is set
      if (grantType === undefined || grantType === null) {
        throw new Error("Missing the required parameter 'grantType' when calling postLogin");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Fields': opts['xFields']
      };
      var formParams = {
        'grant_type': grantType
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/x-www-form-urlencoded', 'multipart/form-data'];
      var accepts = ['application/json'];
      var returnType = Auth;

      return this.apiClient.callApi(
        '/v1/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
