/*
 * Firmatek Downloads API
 * Downloads API for accessing mission Downloads in the Kespry Platform
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.77
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirmatekDownloadsApi);
  }
}(this, function(expect, FirmatekDownloadsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateDownloadRequest', function() {
      beforeEach(function() {
        instance = new FirmatekDownloadsApi.CreateDownloadRequest();
      });

      it('should create an instance of CreateDownloadRequest', function() {
        // TODO: update the code to test CreateDownloadRequest
        expect(instance).to.be.a(FirmatekDownloadsApi.CreateDownloadRequest);
      });

      it('should have the property downloadType (base name: "download_type")', function() {
        // TODO: update the code to test the property downloadType
        expect(instance).to.have.property('downloadType');
        // expect(instance.downloadType).to.be(expectedValueLiteral);
      });

      it('should have the property downloadOptions (base name: "download_options")', function() {
        // TODO: update the code to test the property downloadOptions
        expect(instance).to.have.property('downloadOptions');
        // expect(instance.downloadOptions).to.be(expectedValueLiteral);
      });

    });
  });

}));
